name: lichtenstein_sisal_news
description: "An app for the latest football news"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.0 # Per gestire la navigazione dell'app
  dio: ^5.7.0 # Per le chiamate API
  xml2json: ^6.2.5 # Per transformare il documento XML in JSON per semplcità
  flutter_riverpod: ^2.6.1 # Per lo State Management
  riverpod_annotation: ^2.6.1 
  pretty_dio_logger: ^1.4.0 # Per loggare le chiamate API
  html_unescape: ^2.0.0 # Per i caratteri dell'HTML
  image_picker: ^1.1.2 # Per recuperare l'immagine dal dispositivo
  webview_flutter: ^4.10.0 # Per visualizzare le pagine web
  shared_preferences: ^2.3.3 # Per mantenere i dati permanenti
  path_provider: ^2.1.5 # Per recuperare il percorso della directory dell'app
  path: ^1.9.0 # Per recuperare il nome del file salvato
  external_app_launcher: ^4.0.0 # Per far partire un'app esterna 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1  

flutter:
  uses-material-design: true
